"""Re-annotate the statements that stage 1 could not project.

Three mechanisms, applied to every Chapter 1 case they reach:

* **witness objects + `rel/has`** — "X has a progressively measurable modification"
  registers the modification as an object and links it with HAS. The existential
  import lives in the meaning of `has`, which is how the notes themselves speak.
  This is also what finally produces object-to-object edges.
* **reified facts + `EQUIVALENT`** — an equivalence needs assertions as endpoints,
  and an edge cannot end on an edge, so the two sides of 1.3.12's "if and only if"
  become `:Fact` nodes. Used nowhere else.
* **absorbing quantifier idiom into a property name** — 1.3.13's "there is a set of
  measure one such that for all omega, for all t" is boilerplate shared by every
  almost-sure path statement; it carries no distinguishing information, so it
  becomes `prop/one-sided-limits-as` rather than modelled logic.

Run after the two section seeds.
"""

from pathlib import Path

from stochgraph.annotate import (
    Annotation, Conclusion, Equivalence, ReifiedFact, save_annotation,
)
from stochgraph.concepts import Concept, Registry

GRAPH = Path(__file__).resolve().parents[2] / "Math" / "stochana" / "graph"

C = [
    # --- the HAS relation --------------------------------------------------
    Concept("rel/has", "Relation", "has", arity=2, edge="HAS",
            note="A has B: an object of kind B associated with A exists. Carries "
                 "the existential import, which is the idiom the notes use "
                 "('has a modification', 'has a density')."),

    # --- witness objects ---------------------------------------------------
    Concept("obj/progressive-modification", "Object",
            "progressively measurable modification", refine="Process",
            defined_by="s/1.1.9"),
    Concept("obj/right-continuous-modification", "Object",
            "right-continuous modification", refine="Process",
            defined_by="s/1.3.12"),
    Concept("obj/right-limit-process", "Object", "right-limit process",
            refine="Process", symbol="M_{t+}", defined_by="s/1.3.14"),
    Concept("obj/mean-function", "Object", "mean function", refine="Map",
            symbol="t ↦ E M_t", defined_by="s/1.3.12"),

    # A third sense of right-continuity: of a real function of time. Distinct from
    # a sample path and from a filtration, and the registry is what keeps the three
    # from silently merging.
    Concept("prop/right-continuous-function", "Property",
            "right-continuous function", arity=1, defined_by="s/1.3.12"),
    Concept("prop/one-sided-limits-as", "Property",
            "finite one-sided limits everywhere, almost surely", arity=1,
            defined_by="s/1.3.13"),

    # 1.3.7 concludes the martingale property with respect to a *different*
    # filtration, which a unary `prop/martingale` cannot say. Naming the filtration
    # as a second argument is what makes the change of filtration expressible.
    Concept("rel/martingale-wrt", "Relation", "martingale with respect to",
            arity=2, edge="MARTINGALE_WRT"),
    Concept("obj/right-limit-filtration", "Object", "right-limit filtration",
            refine="SigmaField", symbol="F_{t+}", defined_by="s/1.3.7"),
    Concept("prop/countably-many-jumps", "Property", "at most countably many jumps",
            arity=1, defined_by="ex/5"),
    Concept("rel/equals", "Relation", "equals", arity=2, symbol="=", edge="EQUALS"),
    Concept("obj/elementary-sigma-field", "Object",
            "σ-field generated by the elementary processes", refine="SigmaField",
            defined_by="ex/2"),
    Concept("obj/continuous-sigma-field", "Object",
            "σ-field generated by the continuous processes", refine="SigmaField",
            defined_by="ex/2"),
]

# `modification` reads as a noun; the edge wants a verb.
RETAG = {"rel/modification": "MODIFICATION_OF", "rel/subset-of": "SUBSET_OF",
         "rel/indistinguishable": "INDISTINGUISHABLE_FROM",
         "rel/same-fdd": "SAME_FDD_AS"}

A = [
    # 1.1.9 — "X has a progressively measurable modification".
    Annotation("s/1.1.9", requires=["prop/adapted", "prop/measurable"],
               about=["obj/stochastic-process"],
               defines=["obj/progressive-modification"],
               concludes=[
                   Conclusion("rel/has",
                              args=["obj/stochastic-process",
                                    "obj/progressive-modification"],
                              under=["prop/adapted", "prop/measurable"]),
                   Conclusion("rel/modification",
                              args=["obj/progressive-modification",
                                    "obj/stochastic-process"]),
                   Conclusion("prop/progressively-measurable",
                              args=["obj/progressive-modification"]),
               ]),

    # 1.3.12 — an equivalence between two assertions, so both need identity.
    Annotation("s/1.3.12", requires=["prop/super-martingale",
                                     "prop/usual-conditions"],
               about=["obj/stochastic-process", "obj/mean-function"],
               defines=["obj/right-continuous-modification", "obj/mean-function"],
               facts=[
                   ReifiedFact("a", "rel/has",
                               args=["obj/stochastic-process",
                                     "obj/right-continuous-modification"],
                               gloss="M has a right-continuous modification"),
                   ReifiedFact("b", "prop/right-continuous-function",
                               args=["obj/mean-function"],
                               gloss="t ↦ E M_t is right-continuous"),
               ],
               equivalences=[
                   Equivalence("a", "b",
                               under=["prop/super-martingale",
                                      "prop/usual-conditions"]),
               ],
               concludes=[
                   Conclusion("prop/super-martingale",
                              args=["obj/right-continuous-modification"]),
                   Conclusion("prop/left-limits",
                              args=["obj/right-continuous-modification"]),
               ],
               note="The modification, when it exists, is itself a super-martingale "
                    "and may be chosen with left limits."),

    # 1.3.13 — the quantifier nest is idiom, absorbed into the property.
    Annotation("s/1.3.13", about=["obj/stochastic-process"],
               defines=["prop/one-sided-limits-as"],
               concludes=[Conclusion("prop/one-sided-limits-as",
                                     given=["prop/super-martingale"])],
               note="Stated as 'there is a set of measure one on which, for all t, "
                    "both one-sided limits along the rationals exist and are "
                    "finite' — the standard almost-sure idiom."),

    # Derived objects, now expressible because the derived object is registered.
    Annotation("s/1.2.6", requires=["prop/progressively-measurable",
                                    "prop/stopping-time"],
               about=["obj/stopped-process", "obj/stopped-sigma-field"],
               defines=["obj/stopped-process"],
               concludes=[
                   Conclusion("prop/progressively-measurable",
                              args=["obj/stopped-process"],
                              under=["prop/progressively-measurable",
                                     "prop/stopping-time"]),
               ]),
    Annotation("s/1.3.5", requires=["prop/martingale", "prop/right-continuous-paths",
                                    "prop/uniformly-integrable",
                                    "prop/stopping-time"],
               about=["obj/stopped-process"],
               concludes=[
                   Conclusion("prop/martingale", args=["obj/stopped-process"],
                              under=["prop/martingale",
                                     "prop/right-continuous-paths",
                                     "prop/uniformly-integrable"]),
               ],
               note="Doob's optional sampling. The conditional-expectation identity "
                    "itself is an equation between quantities and has no encoding; "
                    "the stopped-process claim does."),
    # 1.3.7 — same process, different filtration.
    Annotation("s/1.3.7", requires=["prop/martingale", "prop/right-continuous-paths"],
               about=["obj/filtration", "obj/right-limit-filtration"],
               defines=["obj/right-limit-filtration"],
               concludes=[
                   Conclusion("rel/martingale-wrt",
                              args=["obj/stochastic-process",
                                    "obj/right-limit-filtration"],
                              under=["prop/martingale",
                                     "prop/right-continuous-paths"]),
               ]),

    # ex/5 — a genuine claim about càdlàg functions, not merely an instruction.
    Annotation("ex/5", concludes=[
        Conclusion("prop/countably-many-jumps", given=["prop/cadlag"]),
    ]),

    # ex/2 — four generating classes yield the same σ-field. Recorded as equalities
    # against the predictable σ-field rather than as four separate objects.
    Annotation("ex/2", about=["obj/progressive-sigma-field",
                              "obj/predictable-sigma-field"],
               defines=["obj/elementary-sigma-field", "obj/continuous-sigma-field"],
               concludes=[
                   Conclusion("rel/equals", args=["obj/elementary-sigma-field",
                                                  "obj/predictable-sigma-field"]),
                   Conclusion("rel/equals", args=["obj/continuous-sigma-field",
                                                  "obj/predictable-sigma-field"]),
               ],
               note="(ii) the σ-fields generated by adapted left-continuous, "
                    "elementary, predictable-form and continuous processes all "
                    "coincide."),

    Annotation("s/1.3.14", requires=["prop/super-martingale"],
               about=["obj/right-limit-process"],
               defines=["obj/right-limit-process"],
               concludes=[
                   Conclusion("prop/super-martingale",
                              args=["obj/right-limit-process"],
                              under=["prop/super-martingale"]),
                   Conclusion("prop/martingale",
                              args=["obj/right-limit-process"],
                              under=["prop/martingale"]),
               ]),
]


def main() -> int:
    registry = Registry.load(GRAPH)
    problems = []
    for concept in C:
        existing = registry.get(concept.id)
        if existing is not None:
            if existing != concept:
                problems.append(f"{concept.id}: conflicts with the registered entry")
            continue
        problems.extend(registry.accept(concept))
    for cid, edge in RETAG.items():
        concept = registry.get(cid)
        if concept is not None:
            concept.edge = edge
    if problems:
        for problem in problems:
            print("  ", problem)
        return 1
    registry.save(GRAPH)
    for annotation in A:
        save_annotation(annotation, GRAPH)
    print(f"seeded {len(C)} concepts, re-annotated {len(A)} statements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
