"""Stage 1 pass over sections 1.2 and 1.3 — stopping times and martingales.

Run after ``seed_1_1.py``. Reuses that pass's concepts wherever the notes reuse
the idea, which is the point of the registry: `prop/adapted` and
`prop/right-continuous-paths` are the same concepts here as in 1.1.

One aliasing hazard the registry catches: "right-continuous" means one thing of a
*path* and another of a *filtration*. They are separate concepts, and merging them
would make "which results assume right-continuity?" answer a question nobody asked.
"""

from pathlib import Path

from stochgraph.annotate import Annotation, Conclusion, save_annotation
from stochgraph.concepts import Concept, Registry

GRAPH = Path(__file__).resolve().parents[2] / "Math" / "stochana" / "graph"

C = [
    # --- objects ---------------------------------------------------------
    Concept("obj/generated-filtration", "Object", "filtration generated by a process",
            refine="SigmaField", symbol="F̃ᵗ_X", defined_by="s/1.2.2"),
    Concept("obj/stopped-sigma-field", "Object", "stopped σ-field",
            refine="SigmaField", symbol="F_τ", defined_by="s/1.2.3"),
    Concept("obj/first-entrance-time", "Object", "first entrance time",
            refine="Map", symbol="τ_Γ", defined_by="s/1.2.4"),
    Concept("obj/stopped-process", "Object", "stopped process", refine="Process",
            symbol="X^τ", defined_by="s/1.2.6"),

    # --- properties: filtrations and times --------------------------------
    Concept("prop/usual-conditions", "Property",
            "satisfies the usual conditions", arity=1, defined_by="s/1.2.1",
            note="Of a filtration: complete and right-continuous."),
    Concept("prop/complete", "Property", "complete", arity=1,
            defined_by="s/1.2.1", note="Of a filtration."),
    # Deliberately distinct from prop/right-continuous-paths: right-continuity of a
    # filtration and of a sample path are different assertions about different
    # things, and conflating them would corrupt every query over either.
    Concept("prop/right-continuous-filtration", "Property",
            "right-continuous filtration", arity=1, defined_by="s/1.2.1"),
    Concept("prop/stopping-time", "Property", "stopping time", arity=1,
            defined_by="s/1.2.3"),
    Concept("prop/optional-time", "Property", "optional time", arity=1,
            defined_by="s/1.2.3"),

    # --- properties: martingales ------------------------------------------
    Concept("prop/martingale", "Property", "martingale", arity=1,
            defined_by="s/1.3.1"),
    Concept("prop/sub-martingale", "Property", "sub-martingale", arity=1,
            aliases=["submartingale"], defined_by="s/1.3.1"),
    Concept("prop/super-martingale", "Property", "super-martingale", arity=1,
            aliases=["supermartingale"], defined_by="s/1.3.1"),
    Concept("prop/backwards-super-martingale", "Property",
            "backwards super-martingale", arity=1, defined_by="s/1.3.15"),
    Concept("prop/integrable", "Property", "integrable", arity=1,
            aliases=["L1", "L¹"]),
    Concept("prop/uniformly-integrable", "Property", "uniformly integrable",
            arity=1, aliases=["UI"]),
    Concept("prop/lp-bounded", "Property", "Lᵖ-bounded", arity=1,
            aliases=["Lp bounded", "Lp-bounded"]),
    Concept("prop/l1-bounded", "Property", "L¹-bounded", arity=1,
            aliases=["L1 bounded", "L1-bounded"]),
    Concept("prop/closed", "Property", "closed by a terminal random variable",
            arity=1, defined_by="s/1.3.6"),
    Concept("prop/locally-bounded-paths", "Property",
            "sample paths bounded on bounded intervals", arity=1,
            defined_by="s/1.3.4"),
    Concept("prop/left-limits", "Property", "left limits everywhere", arity=1),
    Concept("prop/converges-almost-surely", "Property",
            "converges almost surely", arity=1),
    Concept("prop/converges-in-lp", "Property", "converges in Lᵖ", arity=1),
    Concept("prop/converges-in-l1", "Property", "converges in L¹", arity=1),

    # --- relations ---------------------------------------------------------
    Concept("rel/subset-of", "Relation", "subset of", arity=2, symbol="⊂"),
]

A = [
    # ---------------------------------------------------------------- 1.2
    Annotation("s/1.2.1", defines=["prop/usual-conditions", "prop/complete",
                                   "prop/right-continuous-filtration"],
               about=["obj/filtration"],
               concludes=[
                   Conclusion("prop/complete", given=["prop/usual-conditions"]),
                   Conclusion("prop/right-continuous-filtration",
                              given=["prop/usual-conditions"]),
               ],
               note="The usual conditions are exactly the conjunction, so each "
                    "conjunct follows from them unconditionally."),
    Annotation("s/1.2.2", defines=["obj/generated-filtration"],
               about=["obj/generated-filtration", "obj/stochastic-process"]),
    Annotation("ex/6", about=["obj/generated-filtration"],
               concludes=[Conclusion("prop/right-continuous-filtration",
                                     args=["obj/generated-filtration"],
                                     negated=True)],
               note="The generated filtration is not right-continuous in general."),
    Annotation("s/1.2.3", defines=["prop/stopping-time", "prop/optional-time",
                                   "obj/stopped-sigma-field"],
               about=["obj/filtration", "obj/stopped-sigma-field"]),
    Annotation("ex/7", concludes=[
        Conclusion("prop/optional-time", given=["prop/stopping-time"]),
        Conclusion("prop/stopping-time",
                   given=["prop/optional-time", "prop/right-continuous-filtration"]),
    ], note="i) every stopping time is optional, and the converse holds when the "
            "filtration is right-continuous."),
    Annotation("s/1.2.4", about=["obj/first-entrance-time"],
               defines=["obj/first-entrance-time"],
               concludes=[
                   Conclusion("prop/optional-time",
                              given=["prop/adapted", "prop/right-continuous-paths"]),
                   Conclusion("prop/stopping-time",
                              given=["prop/adapted", "prop/continuous"]),
               ],
               note="Hypotheses on Γ (open / closed) are conditions on a set, not "
                    "on the process, and have no encoding."),
    Annotation("ex/8", about=["obj/first-entrance-time"],
               concludes=[Conclusion("prop/stopping-time",
                                     given=["prop/adapted", "prop/usual-conditions"])],
               note="Entrance time to an open set; the counterexample half shows "
                    "the usual conditions cannot be dropped."),
    Annotation("s/1.2.5", requires=["prop/stopping-time", "prop/optional-time"],
               concludes=[
                   Conclusion("prop/optional-time", given=["prop/stopping-time"]),
               ], note="Closure properties of stopping and optional times under sum, min, max, "
            "inf, sup, limsup, liminf. Closure under an operation is a statement "
            "about a constructed object and is not projected."),
    Annotation("s/1.2.6", requires=["prop/progressively-measurable",
                                    "prop/stopping-time"],
               about=["obj/stopped-process", "obj/stopped-sigma-field"],
               defines=["obj/stopped-process"],
               note="Conclusion is about the stopped process X^τ, a *derived* "
                    "object, so it is not a predicate of the subject and is left "
                    "unprojected."),

    # ---------------------------------------------------------------- 1.3
    Annotation("s/1.3.1", defines=["prop/martingale", "prop/sub-martingale",
                                   "prop/super-martingale"],
               about=["obj/stochastic-process", "obj/filtration"],
               concludes=[
                   Conclusion("prop/adapted", given=["prop/martingale"]),
                   Conclusion("prop/integrable", given=["prop/martingale"]),
               ],
               note="Adaptedness and integrability are part of the definition, so "
                    "they follow from being a martingale unconditionally."),
    Annotation("s/1.3.2", requires=["prop/sub-martingale", "prop/martingale"],
               note="Discrete-time results quoted for reference (Doob's maximal "
                    "inequality, martingale convergence, optional sampling). The "
                    "continuous-time versions are 1.3.3, 1.3.8 and 1.3.5."),
    Annotation("s/1.3.3", requires=["prop/martingale", "prop/right-continuous-paths"],
               note="Doob's maximal inequality. The conclusion is a moment "
                    "inequality, not a predicate — no encoding."),
    Annotation("s/1.3.4", concludes=[
        Conclusion("prop/locally-bounded-paths",
                   given=["prop/martingale", "prop/right-continuous-paths"]),
        Conclusion("prop/locally-bounded-paths",
                   given=["prop/sub-martingale", "prop/right-continuous-paths"]),
    ]),
    Annotation("s/1.3.5", requires=["prop/martingale", "prop/right-continuous-paths",
                                    "prop/uniformly-integrable",
                                    "prop/stopping-time"],
               note="Doob's optional sampling. Conclusions are an identity for "
                    "conditional expectations and a claim about the stopped "
                    "process — both about derived objects."),
    Annotation("s/1.3.6", about=["obj/stochastic-process"],
               requires=["prop/closed"],
               note="Warns that the optional-sampling proof used closedness of the "
                    "*discrete* martingale, not of the continuous-time one."),
    Annotation("ex/9", requires=["prop/sub-martingale", "prop/right-continuous-paths",
                                 "prop/stopping-time"],
               concludes=[Conclusion("prop/integrable",
                                     given=["prop/sub-martingale",
                                            "prop/right-continuous-paths",
                                            "prop/stopping-time"])]),
    Annotation("s/1.3.7", requires=["prop/martingale", "prop/right-continuous-paths"],
               about=["obj/filtration"],
               note="Conclusion is the martingale property with respect to a "
                    "*different* filtration (F_{t+}); the change of filtration has "
                    "no encoding."),
    Annotation("s/1.3.8", concludes=[
        Conclusion("prop/converges-almost-surely",
                   given=["prop/martingale", "prop/right-continuous-paths",
                          "prop/lp-bounded"]),
        Conclusion("prop/converges-in-lp",
                   given=["prop/martingale", "prop/right-continuous-paths",
                          "prop/lp-bounded"]),
        Conclusion("prop/converges-almost-surely",
                   given=["prop/martingale", "prop/continuous", "prop/l1-bounded"]),
    ], note="Martingale convergence. For p = 1 only a.s. convergence holds, and "
            "only under continuity — recorded as the third, separate implication."),
    Annotation("s/1.3.9", requires=["prop/super-martingale"],
               note="Discrete up-crossing lemma; the conclusion bounds the expected "
                    "number of up-crossings — a quantity, not a predicate."),
    Annotation("s/1.3.10", requires=["prop/super-martingale"],
               note="Continuous-time up-crossing lemma; same shape as 1.3.9."),
    Annotation("ex/10", requires=["prop/super-martingale",
                                  "prop/right-continuous-paths"],
               concludes=[Conclusion("prop/left-limits",
                                     given=["prop/super-martingale",
                                            "prop/right-continuous-paths"])]),
    Annotation("s/1.3.11", concludes=[
        Conclusion("prop/converges-almost-surely",
                   given=["prop/sub-martingale", "prop/right-continuous-paths"]),
    ], note="Requires sup E(M_t^+) < ∞, a moment condition with no encoding."),
    Annotation("ex/11", requires=["prop/sub-martingale"],
               note="Proof of 1.3.11."),
    # An equivalence is two sufficiency claims, so both directions are recorded.
    Annotation("ex/12", concludes=[
        Conclusion("prop/converges-in-l1",
                   given=["prop/uniformly-integrable", "prop/sub-martingale",
                          "prop/right-continuous-paths"]),
        Conclusion("prop/uniformly-integrable",
                   given=["prop/converges-in-l1", "prop/sub-martingale",
                          "prop/right-continuous-paths"]),
    ], note="Three equivalent conditions for a non-negative right-continuous "
            "sub-martingale."),
    Annotation("ex/13", concludes=[
        Conclusion("prop/converges-in-l1",
                   given=["prop/uniformly-integrable", "prop/martingale",
                          "prop/right-continuous-paths"]),
        Conclusion("prop/uniformly-integrable",
                   given=["prop/converges-in-l1", "prop/martingale",
                          "prop/right-continuous-paths"]),
        Conclusion("prop/closed",
                   given=["prop/uniformly-integrable", "prop/martingale",
                          "prop/right-continuous-paths"]),
    ], note="Four equivalent conditions for a right-continuous martingale; the "
            "fourth is closedness by a terminal variable."),
    Annotation("s/1.3.12", requires=["prop/super-martingale", "prop/usual-conditions"],
               note="Existence of a right-continuous modification, iff t ↦ E M_t is "
                    "right-continuous. Existential and biconditional — the same gap "
                    "as 1.1.9."),
    Annotation("s/1.3.13", requires=["prop/super-martingale"],
               note="Existence of one-sided limits along the rationals, almost "
                    "surely — an existential claim about sample paths."),
    Annotation("s/1.3.14", requires=["prop/super-martingale"],
               note="Properties of the right-limit process M_{t+}, a derived "
                    "object."),
    Annotation("s/1.3.15", concludes=[
        Conclusion("prop/converges-almost-surely",
                   given=["prop/backwards-super-martingale"]),
        Conclusion("prop/uniformly-integrable",
                   given=["prop/backwards-super-martingale", "prop/l1-bounded"]),
        Conclusion("prop/l1-bounded",
                   given=["prop/backwards-super-martingale",
                          "prop/uniformly-integrable"]),
    ], note="Backwards martingale convergence. Uniform integrability and "
            "L¹-boundedness are equivalent here, so both directions are recorded."),
    Annotation("s/1.3.16", requires=["prop/super-martingale"],
               note="Monotonicity of t ↦ E[M_t^-]; a claim about a quantity."),
    Annotation("s/1.3.17", requires=["prop/super-martingale"],
               concludes=[Conclusion("prop/uniformly-integrable",
                                     given=["prop/super-martingale",
                                            "prop/backwards-super-martingale"])],
               note="The backwards super-martingale along a decreasing sequence is "
                    "uniformly integrable."),
    Annotation("ex/14", note="A conditional-expectation identity; no predicate."),
    Annotation("ex/15", note="Completes the converse in 1.3.12."),
]


def main() -> int:
    registry = Registry.load(GRAPH)
    problems = []
    for concept in C:
        # Idempotent: re-running a pass must be a no-op, not an error. Only a
        # genuine conflict (same id, different content) is worth reporting.
        existing = registry.get(concept.id)
        if existing is not None:
            if existing != concept:
                problems.append(f"{concept.id}: conflicts with the registered entry")
            continue
        problems.extend(registry.accept(concept))
    if problems:
        for problem in problems:
            print("  ", problem)
        return 1
    registry.save(GRAPH)
    for annotation in A:
        save_annotation(annotation, GRAPH)
    print(f"seeded {len(C)} concepts, {len(A)} annotations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
